#pragma push_macro("_CXX_CONCAT")
#pragma push_macro("_CXX_QUOTE")
#pragma push_macro("CXX")
#pragma push_macro("CXX_CLANG")
#pragma push_macro("CXX_CONCAT")
#pragma push_macro("CXX_CPU_ARM_32")
#pragma push_macro("CXX_CPU_ARM_64")
#pragma push_macro("CXX_CPU_ARM")
#pragma push_macro("CXX_CPU_BITS")
#pragma push_macro("CXX_CPU_ID")
#pragma push_macro("CXX_CPU_NAME")
#pragma push_macro("CXX_CPU_PPC_32")
#pragma push_macro("CXX_CPU_PPC_64")
#pragma push_macro("CXX_CPU_PPC")
#pragma push_macro("CXX_CPU_X86_32")
#pragma push_macro("CXX_CPU_X86_64")
#pragma push_macro("CXX_CPU_X86")
#pragma push_macro("CXX_DEBUG")
#pragma push_macro("CXX_ENDIAN_BE")
#pragma push_macro("CXX_ENDIAN_LE")
#pragma push_macro("CXX_ENDIAN_NAME")
#pragma push_macro("CXX_ENDIAN")
#pragma push_macro("CXX_GCC")
#pragma push_macro("CXX_ID")
#pragma push_macro("CXX_MSVC")
#pragma push_macro("CXX_NAME")
#pragma push_macro("CXX_OS_ANDROID")
#pragma push_macro("CXX_OS_APPLE")
#pragma push_macro("CXX_OS_ID")
#pragma push_macro("CXX_OS_IOS")
#pragma push_macro("CXX_OS_LINUX")
#pragma push_macro("CXX_OS_MACOS")
#pragma push_macro("CXX_OS_MICROSOFT")
#pragma push_macro("CXX_OS_NAME")
#pragma push_macro("CXX_OS_WINDOWS")
#pragma push_macro("CXX_OS_WINRT")
#pragma push_macro("CXX_QUOTE")

#undef _CXX_CONCAT
#undef _CXX_QUOTE
#undef CXX
#undef CXX_CLANG
#undef CXX_CONCAT
#undef CXX_CPU_ARM_32
#undef CXX_CPU_ARM_64
#undef CXX_CPU_ARM
#undef CXX_CPU_BITS
#undef CXX_CPU_ID
#undef CXX_CPU_NAME
#undef CXX_CPU_PPC_32
#undef CXX_CPU_PPC_64
#undef CXX_CPU_PPC
#undef CXX_CPU_X86_32
#undef CXX_CPU_X86_64
#undef CXX_CPU_X86
#undef CXX_DEBUG
#undef CXX_ENDIAN_BE
#undef CXX_ENDIAN_LE
#undef CXX_ENDIAN_NAME
#undef CXX_ENDIAN
#undef CXX_GCC
#undef CXX_ID
#undef CXX_MSVC
#undef CXX_NAME
#undef CXX_OS_ANDROID
#undef CXX_OS_APPLE
#undef CXX_OS_ID
#undef CXX_OS_IOS
#undef CXX_OS_LINUX
#undef CXX_OS_MACOS
#undef CXX_OS_MICROSOFT
#undef CXX_OS_NAME
#undef CXX_OS_WINDOWS
#undef CXX_OS_WINRT
#undef CXX_QUOTE